First pull request
wlsf82/EngageSphere-Test-Design-Masterclass-turma-2 pull request #12
Opened 2024-07-12 03:26 UTC by fzancanaro

2024-07-12 03:28 UTC, fzancanaro commented
I added a new doc because I didn't know about this step. Please, check my comments on [FlaviaNotes.md].

2024-07-12 23:14 UTC, wlsf82 requested changes
Muito bem @fzancanaro! 👏🏻 

Deixei comentários ao longo do seu código, os quais creio que irão lhe ajudar a melhorar o design dos testes. 😉

2024-07-12 23:14 UTC, wlsf82 commented on cypress.config.js
> +      framework: "react",
O framework aqui devia ser `create-react-app`.

2024-07-12 23:14 UTC, wlsf82 commented on cypress.config.js
> +module.exports = {
Está falando importar a função `defineConfig` do Cypress, e então, atribuir sua execução ao `module.exports`.

Assim:

```js
const { defineConfig } = require('cypress')

module.exports = defineConfig({
  // configurações aqui.
})

2024-07-12 23:14 UTC, wlsf82 commented on cypress.config.js
> +      defaultCommandTimeout: 10000
Primeio, essa timeout não deve ser definido dentro da função `setupNodeEvents`, e sim como uma propriedade de `e2e`.

Segundo, por qual motivo você está sobrescrevendo o _default_ do Cypress?

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +  it('Should get the correct addresses for all customers in the API response', () => {
De onde surgiram estes casos de teste?

Se seu nível é iniciante, o único teste de API necessário era para o seguinte cenário: `Successfully retrieves customers (e.g., checks for the 200 status code)`.

A propósito, ao executar estes testes em meu ambiente local, os mesmos falham.

Conversarei sobre eles em nosso próximo encontro.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +      url: 'http://localhost:3001/customers?page=1&limit=10&size=All'
Que tal definir a URL da API como uma `env`, dentro do arquivo `cypress.config.js`?

Dessa forma, a mesma não precisaria se repetir em vários testes de API e poderia ser buscada com o modulo `Cypress.env`.

Por exemplo: ``const CUSTOMERS_API_URL = `${Cypress.env('API_URL')}/customers``

E então, tal variável poderia ser reutilizada ao longo dos testes.

A propósito, tal abordagem permitiria a execução dos mesmos testes de API contra diferentes ambientes, com suas diferentes URLs, visto que tal `env` poderia ser sobrescrita via linha de comando, por exemplo.

Algo assim: `cypress run --env API_URL=https://api.example.com`.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +      // Check response status
Este comentário (e outros) são bastante redundantes, visto que a _assertion_ é óbvia.

Reserve comentários para partes do código que não são auto-explicativas.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +    }).then((response) => {
Que tal usar desestruturação de objetos aqui?

Assim:

```js
.then(({ body, status }) => {
  expect(status).to.eq(200);

  expect(body).to.have.property('customers');

 // outras verificações.
})
```

Para aprender mais sobre o assunto, recomendo a seguinte live: [JavaScript para QAs #8 - Atribuição via Desestruturação](https://youtube.com/live/yW1JQoz6PXU?feature=share).

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +      // Check that the response has 'customers'
O mesmo aqui.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/address.cy.js
> +      const expectedAddresses = [
E se os dados do banco de dados forem diferentes?

Ou mesmo, e se houver mais (ou menos clientes) do que o teste espera no banco de dados?

A propósito, não há motivo para testar que cada endereço é retornado.

Para esta API, os comportamentos que devem ser testados são para suas _query strings_, ou seja, `page`, `limit` e `size`, além dos casos de erro.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customerPagination.cy.js
> +describe('Display list of customers by page, page 1 to 10 - 5 custumers per page', () => {
Recomendo dar uma olhada nos casos de teste de API sugeridos [aqui](https://github.com/wlsf82/EngageSphere-Test-Design-Masterclass-turma-2/blob/main/docs/TestCases.md#api).

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customers.cy.js
> +    it('Should get the correct customers without checking the address', () => {
Este é o tipo de cenário que faz sentido para o frontend, não para o backend.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customersAndAddress.cy.js
> +      /*cy.request({
Não versione código comentado.

Isso causa confusão, algo que deve ser evitado em um bom design de testes.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customersAndAddress.cy.js
> +          // Make the API request and assert the response
De novo um comentário de algo óbvio.

Reconsidere seus comentários.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customersAndAddress.cy.js
> +
Evite mais linhas em branco do que o necessário.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/customersAndAddress.cy.js
> +
Uma basta.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/negative.cy.js
> +      }).then((response) => {
O teste de paginação deve verificar só `response.body.pageInfo.currentPage`, nada mais.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/negative.cy.js
> +    const baseUrl = 'http://localhost:3001/customers?';
Legal que definiu uma variável aqui, no entanto, `baseUrl` é o nome usado para a URL do frontend. Esta deveria ser algo como `CUSTOMERS_API_URL`.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/pagination.cy.js
> +    const testPage = (page, limit, expectedCustomers) => {
Essa função gera alta carga cognitiva ao ler o código.

Um teste para paginação já é o suficiente.

Veja um exemplo abaixo:

```js
it('paginates the customer list correctly', () => {
  cy.request('GET', `${CUSTOMERS_API_URL}?page=2`).as('getCustomersPageTwo')

  cy.get('@getCustomersPageTwo')
    .its('body.pageInfo.currentPage')
    .should('eq', '2') // Supposing there are at least 2 pages
})
```

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/pagination.cy.js
> +    testPage(1, 5, 5);
Ao ler a chamada da função, não é possível saber o que é cada parâmetro.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/property.cy.js
> +  it('Check individual properties', () => {
Qual o motivo de testar a mesma coisa em outros testes e depois testar a mesma coisa individualmente em outro teste?

Devemos escrever só o suficiente de testes, para que estes provenham feedback rápidos aos times.

Quanto mais testes, mais tempo para executá-los, portanto, nada de redundância.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/property.cy.js
> +      expect(response.body).to.have.property('customers').that.is.an('array').with.length(10);
Quando uma _assertion_ é tão longa, recomendo quebrar a linha, para ajudar na legibilidade e evitar _scroll_ lateral

Por exemplo:

```suggestion
      expect(response.body)
        .to.have.property('customers')
        .that.is.an('array')
        .with.length(10);
```

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/property.cy.js
> +      expect(response.body).to.have.property('customers').that.is.an('array').with.length(10);
Que tal?

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/property.cy.js
> +        } else {
Este `else` é desnecessário.

Basta verificar as propriedades de `customer.contactInfo` quando esta existir.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/property.cy.js
> +        expect(customer.address).to.have.property('street').that.is.a('string');
E se `customer.address` for `null`?

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeOrder.cy.js
> +    it('Should get customers ordered by size categories', () => {
Ordenação?

Isso é um cenário que faz sentido no frontend, que é a parte da aplicação que oferece tal funcionalidade, não o backend.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeOrder.cy.js
> +        const sortedCustomers = customers.sort((a, b) => {
Testes devem ser lineares, sem lógicas complexas, tais como `customers.sort(...)`.

Quem testa essa lógica?

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeOrder.cy.js
> +        const expectedCustomers = [
Esse monte de dados no teste polui o mesmo.

Caso fossem necessários, o que não é o caso, deveriam ser abstraídos para _fixtures_.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeOrder.cy.js
> +        const expectedCustomers = [
O mesmo vale para todos os casos de teste revisados até então.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeOrder.cy.js
> +          const expectedCustomer = expectedCustomers.find(c => c.id === customer.id);
De novo uma lógica complexa dentro do teste.

Testes devem ser lineares.
Devem possuir pré-condições, ações e resultados esperados.

Nada mais, nada menos.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/e2e/1-getting-started/sizeSmall.cy.js
> +        for (let i = 0; i < orderedSmallCustomers.length - 1; i++) {
De novo lógicas complexas que tornam o teste não-linear.

Recomendo assitir aos vídeos sobre testes de API da [playlist _API Testing_](https://www.youtube.com/playlist?list=PL-eblSNRj0QGkMqsqxUvy7VI4VfXEUp-G) no Canal TAT.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/fixtures/example.json
> +{
Que tal deletar as fixtures visto que elas não estão em uso?

Ao fazer isso, ajuste o arquivo `cypress.config.js` com a propriedade `fixturesFolder: false`.

2024-07-12 23:14 UTC, wlsf82 commented on cypress/support/commands.js
> +   Cypress.on('uncaught:exception', (err, runnable) => {
Por qual motivo você está fazendo isso?

Tal código pode mascarar reais erros da aplicação.

Evite isso.

2024-07-12 23:14 UTC, wlsf82 commented on frontend/src/components/CustomerDetails.cy.js
> +import React from 'react'
Seus testes de componentes estão falhando.

Farei uma demo durante o próximo encontro, o qual creio que vai ajudá-la a entender mais sobre o assunto, no entanto, você não deveria estar se preocupando com tal tipo de teste, se escolheu pelos exercícios do nível iniciante.

Em vez disso, recomendo focar nos testes de GUI (E2E) de tal nível.

2024-07-12 23:14 UTC, wlsf82 commented on frontend/src/index.js
> +
```suggestion
```

2024-07-12 23:14 UTC, wlsf82 commented on package.json
> +    "react": "^18.3.1",
Estas deveriam ser `devDependencies` também.

2024-07-12 23:14 UTC, wlsf82 commented on webpack.config.js
> +// webpack.config.js
Este arquivo não deveria ser necessário.

2024-07-20 10:53 UTC, closed without merging

2024-07-23 15:10 UTC, wlsf82 commented
Oi @fzancanaro, por qual motivo você fechou o PR?

A idéia do exercício era que você implementasse as melhorias sugeridas no mesmo PR, fizesse novos commits e então eu faria um novo _round_ de _code review_.